# dependencies and compiler to import other smartcontracts in my contract
dependencies:
  # - <organization/repo>@<version>
  - smartcontractkit/chainlink-brownie-contracts@1.1.1

compiler:
  solc:
    remappings:
      # whenever chainlink is imported in my contract, dependencies above will be executed
      - '@chainlink=smartcontractkit/chainlink-brownie-contracts@1.1.1'

# if warning sign below pops up when compile
# `Unable to compile smartcontractkit/chainlink-brownie-contracts@1.1.1 due to a NamespaceCollision`
# remove all the files in build directory

dotenv: .env
networks:
  default: development
  rinkeby:
    eth_usd_price_feed: "0x8A753747A1Fa494EC906cE90E9f37563A8AF630e"
    verify: True
  mainnet-fork-dev:
    eth_usd_price_feed: "0x5f4eC3Df9cbd43714FE2740f5E3616155c5b8419"
    verify: False
  development:
    verify: False
    cmd_settings:
      accounts: 50
wallets:
  from_key: ${PRIVATE_KEY}

